FROM alpine:latest AS certs
RUN apk add --no-cache ca-certificates && update-ca-certificates 2>/dev/null || true

FROM scratch

COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

COPY tsdproxyd /
COPY healthcheck /

ENTRYPOINT ["/tsdproxyd"]
EXPOSE 8080
HEALTHCHECK CMD [ "/healthcheck" ]
